package errors_test

import "testing"

func TestWarn(t *testing.T){
	Warn("pass") //cause assertion error."
}
